# Generated by Django 6.0.7 on 2026-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FairMatrix',
            new_name='FareMatrix',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat_number')},
        ),
    ]
